channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - tabulate
  - pandoc >=2.11
  - pandoc-crossref >=0.3.10
  - pytest
  - cookiecutter
  - watermark
  - tectonic
  - pip
  - pip:
    - pandoc-include
    - pandoc-latex-admonition
