name: {{ cookiecutter.conda_environment }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{cookiecutter.python_version}}
  - jupyter                         # necessary to run notebooks
  - jupyterlab                      # necessary to run notebooks
  - pandas >=1.0                    # generate markdown tables
  - tabulate                        # generate markdown tables
  - pandoc >=2.7                    # necessary to compile the paper
  - pandoc-crossref                 # necessary to compile the paper
  - tectonic =0.1.14                # necessary to compile the paper
  - watermark                       # add metadata to notebooks
  - seaborn                         # requirement of stargazer and we want from conda not pip
  - gh
  - pip
  - pip:
    - pandoc-include                 # necessary to compile the paper
    - pandoc-latex-admonition        # necessary to compile the paper
    - stargazer
